site_name: Sistemas de BigData
site_url: https://alapvi.github.io

nav:
  - Introducción: index.md
  - Almacenamiento de datos. NoSQL: 
    - NoSQL: nosql/nosql.md
  - MongoDB: mongodb/mongodb.md

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo_peq.png
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - tags
  - search
  #- minify:
  #    minify_html: true
  #    minify_js: true
  #    minify_css: true
  #    htmlmin_opts:
  #        remove_comments: true
  #    cache_safe: true

markdown_extensions:
  - toc:
      permalink: true
